name: GitOps Patch
description: Update GitOps repo values and commit changes

inputs:
  tags:
    description: Image tag to apply
    required: true
  cmd:
    description: Command to patch GitOps files (usually yq)
    required: true

runs:
  using: composite
  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y yq

    - name: Patch GitOps files
      shell: bash
      run: |
        echo "Patching GitOps files with tag: ${{ inputs.tags }}"
        eval "${{ inputs.cmd }}"

    - name: Commit and push changes
      shell: bash
      run: |
        git config user.name "gitops-bot"
        git config user.email "gitops@company.com"

        if git diff --quiet; then
          echo "No changes detected. Skipping commit."
          exit 0
        fi

        git add .
        git commit -m "gitops: update image tag to ${{ inputs.tags }}"
        git push
